<?php


namespace Tests\Feature\sDeliverOrderPlacement;


use Tests\Feature\FeatureTestCase;

class OrderPlacementAPITest extends FeatureTestCase
{
    public function setUp()
    {
        parent::setUp();
        $this->CreatePosOrder();
        // TODO: Change the autogenerated stub
    }

    public function testDummy()
    {
    dd($this->CreatePosOrder());
        $this->assertEquals(1,1);
    }

}