<?php

namespace App\Http\Requests;


class SmsCampaignRequest extends ApiRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    public function all()
    {
        $all = parent::all();
        return $all; // TODO: Change the autogenerated stub
    }
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => 'required',
            'message' => 'required',
            'customers' => 'required|array',
            'customers.*.mobile' => 'required|mobile:bd',
//            'sms_count' => 'required'
        ];
    }

    public function messages()
    {
        $messages = parent::messages(); // TODO: Change the autogenerated stub
        return $messages;
    }
}
