<?php namespace App\Http\Requests;

use Carbon\Carbon;
use Illuminate\Http\Request as HttpRequest;

class SpLoanRequest extends ApiRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    public function all()
    {
        $all = parent::all();
        return $all; // TODO: Change the autogenerated stub`
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        if(HttpRequest::segment(5) == "personal-info") {
            $rules = [
                'gender' => 'required|string|in:Male,Female,Other,পুরুষ,মহিলা,অন্যান্য',
                'dob' => 'required|date|date_format:Y-m-d|before:' . Carbon::today()->format('Y-m-d'),
                'address' => 'required|string',
                'permanent_address' => 'required|string',
                'father_name' => 'required_without:spouse_name',
                'spouse_name' => 'required_without:father_name',
                'occupation' => 'required|string',
                'monthly_living_cost' => 'required|numeric',
                'total_asset_amount' => 'required|numeric',
                'monthly_loan_installment_amount' => 'required|numeric',
            ];
        }

        return $rules;
    }

    public function messages()
    {
        $messages = parent::messages(); // TODO: Change the autogenerated stub
        return $messages;
    }
}
