<?php namespace Sheba\MovieTicket;

class Actions
{
    const GET_MOVIE_LIST = 'GET_MOVIE_LIST';
    const GET_THEATRE_LIST = 'GET_THEATRE_LIST';
    const GET_THEATRE_SEAT_STATUS = 'GET_THEATRE_SEAT_STATUS';
    const REQUEST_MOVIE_TICKET_SEAT = 'REQUEST_MOVIE_TICKET_SEAT';
    const UPDATE_MOVIE_SEAT_STATUS = 'UPDATE_MOVIE_SEAT_STATUS';
    const GET_VENDOR_BALANCE = 'GET_VENDOR_BALANCE';
}