<?php namespace Tests\Feature\OrderManagement;

use App\Models\Resource;
use Tests\Feature\FeatureTestCase;

class NewOrderLIstTest extends FeatureTestCase
{

    public function setUp()
    {
        parent::setUp();
        $this->logIn();// TODO: Change the autogenerated stub
    }

    public function testWithoutFliterResponseCode()
    {
        $response=$this->get("/v1/partners/".$this->partner->id."/order-requests?remember_token=".$this->resource->remember_token);
        $data = $response->decodeResponseJson();
        $this->assertEquals(400, $data['code']);
        $this->assertEquals("The filter field is required.", $data['message']);
    }
    public function testEmptyOrderListResponseCode()
    {
        $response = $this->get("/v1/partners/".$this->partner->id."/order-requests?remember_token=".$this->resource->remember_token."&filter=all");
        $data = $response->decodeResponseJson();
        $this->assertEquals(200,$data['code']);
        $this->assertEquals("Successful",$data['message']);
        $this->assertEquals(0,count($data['orders']));
    }
}