<?php

return [
    "available_payment_gateway_keys" => ["ssl", "bkash"],
    'category_list' => [
        'ssl' => [
            'nid_selfie'  => 'NIDSelfie',
            'institution' => 'Institution',
            'personal'    => 'Personal',
            'documents'   => 'Documents'
        ],
        'bkash' => [
            'nid_selfie'  => 'NIDSelfie',
            'institution' => 'Institution',
            'personal'    => 'Personal',
            'documents'   => 'Documents'
        ],
    ],
    'exclude_form_keys' => [
        'ssl' => [
            'institution' => [],
            'nid_selfie' => [],
            'personal' => [],
            'documents' => [],
        ],
        'bkash' => [
            'institution' => [],
            'nid_selfie' => [],
            'personal' => [],
            'documents' => [],
        ]
    ],
    'category_titles'                    => [
        'nid_selfie'  => [
            'en' => 'NID and Selfie',
            'bn' => 'জাতীয় পরিচয়পত্র ও সেলফি'
        ],
        'institution' => [
            'en' => 'Institution',
            'bn' => 'প্রতিষ্ঠান সম্পর্কিত তথ্য'
        ],
        'personal'    => [
            'en' => 'Personal',
            'bn' => 'ব্যক্তিগত তথ্য '
        ],
        'documents'   => [
            'en' => 'Documents',
            'bn' => 'প্রয়ােজনীয় ডকুমেন্ট'
        ]
    ],
    "category_form_items" => [
        'institution' => [
            [
                'id'          => 'header',
                'input_type'  => 'header',
                "message"     => "কোম্পানি প্রোফাইল",
                "hint"        => "",
                'mandatory'   => false,
                'is_editable' => false,
            ],
            [
                'label'         => 'কোম্পানির নাম * ',
                'message'       => '',
                'hint'          => 'কোম্পানির নাম লিখুন',
                'id'            => 'company_name',
                'error'         => "কোম্পানির নাম পূরণ আবশ্যক",
                'input_type'    => 'text',
                'data'          => '',
                "min_length"    => "",
                "max_length"    => "",
                'is_editable'   => true,
                'mandatory'     => false,
                'data_source'   => 'partner',
                'data_source_id'=> 'name'
            ],
            [
                'label'         => 'ট্রেড লাইসেন্স নং *',
                'message'       => '',
                'hint'          => 'ট্রেড লাইসেন্স নং লিখুন',
                'id'            => 'trade_license',
                'error'         => "ট্রেড লাইসেন্স নং পূরণ আবশ্যক",
                'input_type'    => 'text',
                'data'          => '',
                "min_length"    => "",
                "max_length"    => "",
                'is_editable'   => true,
                'mandatory'     => true,
                'data_source'   => 'partner_basic_information',
                'data_source_id'=> 'trade_license'
            ],
            [
                'label'         => 'কোম্পানির টাইপ *',
                'message'       => '',
                'hint'          => '',
                'id'            => 'company_type',
                'error'         => "কোম্পানির টাইপ পূরণ আবশ্যক",
                'input_type'    => 'dropdown',
                'data'          => '',
                "min_length"    => "",
                "max_length"    => "",
                'is_editable'   => true,
                'mandatory'     => false,
                'data_source'   => 'partner',
                'data_source_id'=> 'business_type'
            ],
            [
                'label'         => 'রেজিস্টার্ড ঠিকানা *',
                'message'       => "",
                'hint'          => 'কোম্পানির ঠিকানা লিখুন',
                'id'            => 'registered_address',
                'error'         => "রেজিস্টার্ড ঠিকানা পূরণ আবশ্যক",
                'input_type'    => 'text',
                'data'          => "",
                "min_length"    => "",
                "max_length"    => "",
                'is_editable'   => true,
                'mandatory'     => false,
                'data_source'   => 'partner',
                'data_source_id'=> 'address'
            ],
            [
                'label'            => 'সাপোর্ট নাম্বার *',
                'message'          => '',
                'hint'             => '01762180533',
                'id'               => 'support_number',
                'error'            => "সাপোর্ট নাম্বার পূরণ আবশ্যক",
                'input_type'       => 'phone',
                'data'             => "",
                "min_length"       => "",
                "max_length"       => "",
                'is_editable'      => false,
                'mandatory'        => false,
                'data_source'      => 'partner',
                'data_source_id'   => 'getContactNumber',
                'data_source_type' => 'function'
            ],
            [
                'label'            => 'আপনি ব্যবসা শুরু করেছেন কবে *',
                'message'          => '',
                'hint'             => '05/11/2012',
                'id'               => 'registration_year',
                'error'            => "পূরণ আবশ্যক",
                'input_type'       => 'date_picker',
                'data'             => "",
                "min_length"       => "",
                "max_length"       => "",
                'is_editable'      => false,
                'mandatory'        => false,
                'data_source'      => 'partner_basic_information',
                'data_source_id'   => 'registration_year'
            ],
            [
                'label'            => 'কোম্পানির মোট মূল্য (আনুমানিক) *',
                'message'          => "",
                'hint'             => 'কোম্পানির মোট মূল্য লিখুন',
                'id'               => 'company_total_value',
                'error'            => "পূরণ আবশ্যক",
                'input_type'       => 'number',
                'data'             => "",
                "min_length"       => "",
                "max_length"       => "",
                'is_editable'      => false,
                'mandatory'        => false,
                'data_source'      => 'json'
            ],
            [
                'label'            => "মার্চেন্টের ধরণ",
                'message'          => '',
                'hint'             => '',
                'id'               => 'type_of_merchant',
                'error'            => "পূরণ আবশ্যক",
                'input_type'       => 'text',
                'data'             => "MSME",
                "min_length"       => "",
                "max_length"       => "",
                'is_editable'      => false,
                'mandatory'        => false,
                'data_source'      => 'json'
            ],
            [
                'id'          => 'header',
                'input_type'  => 'header',
                "message"     => "কোম্পানির ব্যাংক তথ্য",
                "hint"        => "",
                'mandatory'   => false,
                'is_editable' => false,
            ],
            [
                'label'            => "ব্যাংক অ্যাকাউন্টের নাম *  ",
                'message'          => "",
                'hint'             => 'অ্যাকাউন্টের নাম লিখুন',
                'id'               => 'acc_name',
                'error'            => "অ্যাকাউন্টের নাম পূরণ আবশ্যক",
                'input_type'       => 'text',
                'data'             => "",
                "min_length"       => "",
                "max_length"       => "",
                'is_editable'      => false,
                'mandatory'        => false,
                'data_source'      => 'partner_bank_information',
                'data_source_id'   => 'acc_name'
            ],
            [
                'label'            => "ব্যাংকের নাম",
                'message'          => "",
                'hint'             => 'ব্যাংকের নাম লিখুন',
                'id'               => 'bank_name',
                'error'            => "ব্যাংকের নাম পূরণ আবশ্যক",
                'input_type'       => 'text',
                'data'             => "",
                "min_length"       => "",
                "max_length"       => "",
                'is_editable'      => false,
                'mandatory'        => false,
                'data_source'      => 'partner_bank_information',
                'data_source_id'   => 'bank_name'
            ],
            [
                'label'            => "ব্যাংকের ঠিকানা ",
                'message'          => "",
                'hint'             => "ব্যাংকের ঠিকানা লিখুন",
                'id'               => 'bank_address',
                'error'            => "ব্যাংকের ঠিকানা পূরণ আবশ্যক",
                'input_type'       => 'text',
                'data'             => "",
                "min_length"       => "",
                "max_length"       => "",
                'is_editable'      => false,
                'mandatory'        => false,
                'data_source'      => 'partner_bank_information',
                'data_source_id'   => 'bank_address'
            ],
            [
                'label'            => "ব্যাংক অ্যাকাউন্ট নং *",
                'message'          => "",
                'hint'             => "অ্যাকাউন্ট নং লিখুন",
                'id'               => 'acc_no',
                'error'            => "ব্যাংক অ্যাকাউন্ট নং পূরণ আবশ্যক",
                'input_type'       => 'text',
                'data'             => "",
                "min_length"       => "",
                "max_length"       => "",
                'is_editable'      => false,
                'mandatory'        => false,
                'data_source'      => 'partner_bank_information',
                'data_source_id'   => 'acc_no'
            ],
            [
                'label'            => "ব্যাংক রাউটিং নাম্বার *",
                'message'          => "",
                'hint'             => "রাউটিং নাম্বার লিখুন",
                'id'               => 'routing_no',
                'error'            => "ব্যাংক রাউটিং নাম্বার পূরণ আবশ্যক",
                'input_type'       => 'text',
                'data'             => "",
                "min_length"       => "",
                "max_length"       => "",
                'is_editable'      => false,
                'mandatory'        => false,
                'data_source'      => 'partner_bank_information',
                'data_source_id'   => 'routing_no'
            ],
            [
                'id'          => 'header',
                'input_type'  => 'header',
                "message"     => "লেনদেন সম্পর্কিত তথ্য",
                "hint"        => "",
                'mandatory'   => false,
                'is_editable' => false,
            ],
            [
                'label'            => "আপনার ব্যবসাতে প্রতি মাসে কয়টি লেনদেন হয় * ",
                'message'          => "",
                'hint'             => "মাসিক লেনদেনের পরিমাণ লিখুন",
                'id'               => 'monthly_transaction_numbers',
                'error'            => "পূরণ আবশ্যক",
                'input_type'       => 'number',
                'data'             => "",
                "min_length"       => "",
                "max_length"       => "",
                'is_editable'      => false,
                'mandatory'        => false,
                'data_source'      => 'json',
            ],
            [
                'label'            => "আপনার ব্যবসাতে প্রতি মাসে কত টাকার লেনদেন হয় * ",
                'message'          => "",
                'hint'             => "মাসিক লেনদেনের পরিমাণ লিখুন",
                'id'               => 'monthly_transaction_amount',
                'error'            => "পূরণ আবশ্যক",
                'input_type'       => 'decimal_number',
                'data'             => "",
                "min_length"       => "",
                "max_length"       => "",
                'is_editable'      => false,
                'mandatory'        => false,
                'data_source'      => 'json',
            ],
            [
                'label'            => "আপনার ব্যবসাতে ১ টি লেনদেন এ সর্বোচ্চ লেনদেন হয় *",
                'message'          => "",
                'hint'             => "সর্বোচ্চ ১তি লেনদেনের পরিমাণ লেখুন",
                'id'               => 'height_transaction_amount',
                'error'            => "পূরণ আবশ্যক",
                'input_type'       => 'decimal_number',
                'data'             => "",
                "min_length"       => "",
                "max_length"       => "",
                'is_editable'      => false,
                'mandatory'        => false,
                'data_source'      => 'json',
            ],
            [
                'label'            => "আপনার ব্যবসাতে প্রতি দিনে কয়টি লেনদেন হয় *",
                'message'          => "",
                'hint'             => "প্রতিদিনের লেনদেনের পরিমাণ লিখুন",
                'id'               => 'daily_transaction_number',
                'error'            => "পূরণ আবশ্যক",
                'input_type'       => 'number',
                'data'             => "",
                "min_length"       => "",
                "max_length"       => "",
                'is_editable'      => false,
                'mandatory'        => false,
                'data_source'      => 'json',
            ],
            [
                'label'            => "আপনার ব্যবসাতে প্রতি দিনে কত টাকার লেনদেন হয় *",
                'message'          => "",
                'hint'             => "দৈনিক লেনদেনের পরিমাণ লিখুন",
                'id'               => 'daily_transaction_amount',
                'error'            => "পূরণ আবশ্যক",
                'input_type'       => 'decimal_number',
                'data'             => "",
                "min_length"       => "",
                "max_length"       => "",
                'is_editable'      => false,
                'mandatory'        => false,
                'data_source'      => 'json',
            ],
        ],
    ],

];