<?php


namespace Tests\Feature\OfficeSettings;


use Tests\Feature\FeatureTestCase;

class HolidaySettingsTest extends FeatureTestCase
{

    public function setUp()
    {
        parent::setUp();
        $this->logIn();// TODO: Change the autogenerated stub
    }
    public function testSuccessfulResponseCode()
    {
        $response = $this->get('/v2/businesses/1/holidays',[
            'Authorization' => "Bearer $this->token"
        ]);
        $data= $response->decodeResponseJson();
        $this->assertEquals(200,$data['code']);
        $this->assertEquals('Successful',$data['message']);
    }
    public function testBusinessHolidaysResponseWhenNoDataAvailableInDB()
    {
        $response = $this->get('/v2/businesses/1/holidays',[
            'Authorization' => "Bearer $this->token"
        ]);
        $data = $response->decodeResponseJson();

        $this->assertEquals([] ,$data['business_holidays']);
    }

}