<?php


namespace Sheba\NeoBanking\DTO;


use ArrayObject;
use Sheba\NeoBanking\Exceptions\InvalidListInsertion;

class BankFormCategoryList extends ArrayObject
{
    /**
     * @param mixed $value
     * @throws InvalidListInsertion
     */
    public function append($value)
    {
        if (!($value instanceof BankFormCategory)) throw new InvalidListInsertion();
        parent::append($value); // TODO: Change the autogenerated stub
    }

}
