<?php

namespace Tests\Feature\Digigo\Announcement;

use Tests\Feature\FeatureTestCase;

/**
 * @author Khairun Nahar <khairun@sheba.xyz>
 */

class AnnouncementsListGetApiTest extends FeatureTestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->logIn();
    }

    public function testCheckAPiReturnAnnouncementsListAccordingToLimitParams()
    {
        $response = $this->get("/v1/employee/dashboard", [
            'Authorization' => "Bearer $this->token",
        ]);
        $data = $response->decodeResponseJson();
        dd( $data);
        $this->assertEquals(200, $data['code']);
        $this->assertEquals('Successful', $data['message']);
    }

}
