<?php


namespace Tests\Feature\sDeliveryOrderManagement;


use App\Models\PosCustomer;
use App\Models\PosOrder;
use App\Sheba\Partner\Delivery\DeliveryServerClient;
use Tests\Feature\FeatureTestCase;
use Tests\Mocks\MockDeliveryServerClient;

class DeliveryOrderStatusAPITest extends FeatureTestCase


{

    public function setUp()
    {
        parent::setUp();// TODO: Change the autogenerated stub
        $this->logIn();

       $this->partnerPosCustomer = factory(PosCustomer::class)->create();
       $this->posOrderCreate = factory(PosOrder::class)->create();
       $this->app->singleton(DeliveryServerClient::class,MockDeliveryServerClient::class);

    }


    public function testGetDeliveryOrderStatusUpdate()
    {

        $response = $this->get('/v2/pos/delivery/delivery-status?pos_order_id=1',  [
            'Authorization' => "Bearer $this->token"
        ]);
        $data = $response->decodeResponseJson();
       // dd($data);
        $this->assertEquals(200, $data['code']);
        $this->assertEquals("Successful", $data['message']);

    }
}