<?php namespace Feature\TopUp;


use App\Models\Affiliate;
use App\Models\Location;
use App\Models\Profile;
use Tests\Feature\FeatureTestCase;

class SingleTopUpTest extends FeatureTestCase
{
    private $profile;
    private $affiliate;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->profile = factory(Profile::class)->create();
        $this->affiliate=factory(Affiliate::class)->create();

        
    }

    public function testSuccessfulResponseCode()
    {


    }

}