<?php namespace Feature\TopUp;


use App\Models\Location;
use App\Models\Profile;
use Tests\Feature\FeatureTestCase;

class SingleTopUpTest extends FeatureTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $profile = factory(Profile::class->create());

    }

}