<?php namespace Feature\TopUp;


use App\Models\Location;
use Tests\Feature\FeatureTestCase;

class SingleTopUpTest extends FeatureTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $profile = factory(Location::class->create());
        
    }

}