version: '3.5'
services:
  upgraded-api-service:
    image: registry.sheba.xyz/${CONTAINER_NAME}
    environment:
      SERVICE_NAME: app
    ports:
      - ${PORT}:80

networks:
  upgraded-api-service-network:
    driver: bridge
