<?php


namespace Sheba\Loan\DS;


class PermanentAddress extends Address
{
    public function __construct($info)
    {
        parent::__construct($info->permanent_address);
    }
    public function toArray()
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }
}
