<?php


namespace Sheba\Loan\DS;


class PresentAddress extends Address
{
    public function __construct($info)
    {
        parent::__construct($info->present_address);
    }

    public function toArray()
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }

}
