<?php namespace Sheba\Business\AttendanceActionLog\ActionChecker;

use Carbon\Carbon;
use Sheba\Business\AttendanceActionLog\WeekendHolidayByBusiness;
use Sheba\Business\Leave\HalfDay\HalfDayLeaveCheck;
use Sheba\Dal\AttendanceActionLog\Actions;

class CheckOut extends ActionChecker
{
    public function getActionName()
    {
        return Actions::CHECKOUT;
    }

    protected function setAlreadyHasActionForTodayResponse()
    {
        $this->setResult(ActionResultCodes::ALREADY_CHECKED_OUT, ActionResultCodeMessages::ALREADY_CHECKED_OUT);
    }

    public function check()
    {
        parent::check(); // TODO: Change the autogenerated stub
        $this->checkAlreadyCheckedIn();
        $this->checkLeftEarly();
    }

    private function checkAlreadyCheckedIn()
    {
        if (!$this->isSuccess()) return;
        if (!$this->hasCheckedIn()) $this->setResult(ActionResultCodes::CHECKIN_FIRST, ActionResultCodeMessages::CHECKIN_FIRST);
    }

    private function hasCheckedIn()
    {
        return $this->attendanceLogsOfToday ? $this->attendanceLogsOfToday->filter(function ($log) {
                return $log->action == Actions::CHECKIN;
            })->count() > 0 : false;
    }

    protected function setSuccessfulResponseMessage()
    {
        $this->setResult(ActionResultCodes::SUCCESSFUL, ActionResultCodeMessages::SUCCESSFUL_CHECKOUT);
    }

    protected function checkLeftEarly()
    {
        $date = Carbon::now();
        $weekendHoliday = new WeekendHolidayByBusiness();

        $which_half_day = (new HalfDayLeaveCheck())->setBusinessMember($this->businessMember)->checkHalfDayLeave();
        $today_last_checkout_time = $this->business->calculationTodayLastCheckOutTime($which_half_day);

        if (is_null($today_last_checkout_time)) return;
        if (!$this->isSuccess()) return;

        $today_checkout_time_without_second = Carbon::parse($date->format('Y-m-d H:i'));

        if ($today_checkout_time_without_second->lessThan(Carbon::parse($today_last_checkout_time))) {
            if ($weekendHoliday->isWeekendByBusiness($date) || $weekendHoliday->isHolidayByBusiness($date)) {
                $this->setResult(ActionResultCodes::SUCCESSFUL, ActionResultCodeMessages::SUCCESSFUL_CHECKOUT);
            } else {
                $this->setResult(ActionResultCodes::LEFT_EARLY_TODAY, ActionResultCodeMessages::LEFT_EARLY_TODAY);
            }
        }
    }
}
