<?php namespace Sheba\Business\AttendanceActionLog\ActionChecker;

use Carbon\Carbon;
use Sheba\Business\AttendanceActionLog\Time;
use Sheba\Business\AttendanceActionLog\TimeByBusiness;
use Sheba\Dal\AttendanceActionLog\Actions;

class CheckIn extends ActionChecker
{
    public function getActionName()
    {
        return Actions::CHECKIN;
    }

    public function check()
    {
        parent::check(); // TODO: Change the autogenerated stub
        $this->checkForLateAction();
    }

    protected function setAlreadyHasActionForTodayResponse()
    {
        $this->setResult(ActionResultCodes::ALREADY_CHECKED_IN, ActionResultCodeMessages::ALREADY_CHECKED_IN);
    }

    protected function setSuccessfulResponseMessage()
    {
        $this->setResult(ActionResultCodes::SUCCESSFUL, ActionResultCodeMessages::SUCCESSFUL_CHECKIN);
    }

    protected function checkForLateAction()
    {
        $time = new TimeByBusiness();
        $last_checkin_time = $time->getOfficeStartTimeByBusiness();
        if (is_null($last_checkin_time)) return;
        if (!$this->isSuccess()) return;
        if (Carbon::now() > Carbon::parse($last_checkin_time)) $this->setResult(ActionResultCodes::LATE_TODAY, ActionResultCodeMessages::LATE_TODAY);
    }
}
