<?php namespace Sheba\Business\AttendanceActionLog\ActionChecker;

use Sheba\Dal\AttendanceActionLog\Actions;

class CheckOut extends ActionChecker
{
    public function getActionName()
    {
        return Actions::CHECKOUT;
    }

    protected function setAlreadyHasActionForTodayResponse()
    {
        $this->setResult(ActionResultCodes::ALREADY_CHECKED_OUT, ActionResultCodeMessages::ALREADY_CHECKED_OUT);
    }

    public function check()
    {
        parent::check(); // TODO: Change the autogenerated stub
        $this->checkAlreadyCheckedIn();
        $this->checkLeftEarly();
    }

    private function checkAlreadyCheckedIn()
    {
        if (!$this->isSuccess()) return;
        if (!$this->hasCheckedIn()) $this->setResult(ActionResultCodes::CHECKIN_FIRST, ActionResultCodeMessages::CHECKIN_FIRST);
    }

    private function hasCheckedIn()
    {
        return $this->attendanceLogsOfToday ? $this->attendanceLogsOfToday->filter(function ($log) {
                return $log->action == Actions::CHECKIN;
            })->count() > 0 : false;
    }

    protected function setSuccessfulResponseMessage()
    {
        $this->setResult(ActionResultCodes::SUCCESSFUL, ActionResultCodeMessages::SUCCESSFUL_CHECKOUT);
    }

    protected function checkLeftEarly()
    {
        // TODO: Implement checkForLateAction() method.
    }
}
